language: python
python:
  - 2.6
  - 3.7

install:
  - pip install mkdocs
  - pip install mkdocs-material

script:
  - mkdocs build --verbose --clean --strict

after_success:
  deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   local_dir: site
   on:
     branch: master
