matrix:
  include:
    - stage: test
      language: julia
      julia:
        - 0.6
      after_success:
        - stage: deploy
          language: python
          if: branch = master
          install:
            - pip install mkdocs
            - pip install mkdocs-material
          script:
            - mkdocs build --verbose --clean --strict
          deploy:
           provider: pages
           skip_cleanup: true
           github_token: $GITHUB_TOKEN
           local_dir: site
           on:
             branch: master
